Processamento pagamento online
jacksonmotazup/pagamentos pull request #5
Opened 2021-11-12 14:10 UTC by jacksonmotazup

2021-11-12 14:13 UTC, rafaelpontezup commented on src/main/java/br/com/zup/pagamentos/gateway/RedirecionadorGateways.java
> +        var gatewayEscolhido = this.retornaGatewayMenorTaxa(gateways, transacao.getValor());
esse nome "retorna" num metodo eh bem estranho, hehe :-)

pode pensar num nome melhor? tipo calcula, encontra, resolve, analisa etc.

2021-11-12 14:30 UTC, rafaelpontezup requested changes
sugestoes pertinentes!

2021-11-12 14:30 UTC, rafaelpontezup commented on src/main/java/br/com/zup/pagamentos/gateway/SaoriGateway.java
> +        transacao.conclui();
aqui tem 2 problemas que enxergo:
1. o objeto de input `transacao` está sendo alterado por essa logica;
2. vc está invocando 2 métodos para executar a operação em si (`ajustaValorAposTaxa()` e `conclui()`);

pro item 1, um gateway eh responsavel por se comunicar com um serviço externo (http, grpc, socket etc), e não executar logica de negocio na sua app. com base na resposta do gateway eh que vc app toma uma decisão e altera estado no sistema;

pro item 2, pq nao ter um unico metodo que faz essa operação de forma atomica? ter que invocar método em detemrinada ordem geralmente eh muito ruim para um design. talvez ter um metodo como `paga(taxa)` e dentro dele vc invoca os metodos que quiser de forma privada (encapsulamento).

2021-11-12 14:30 UTC, rafaelpontezup commented on src/main/java/br/com/zup/pagamentos/gateway/TangoGateway.java
> +        if (valor.doubleValue() <= 100) {
no geral eh perigoso manipular logica financeiras como `double`. vc tem um `BigDecimal` mas converte pra `double` pra  favorece-lo.

2021-11-12 14:30 UTC, rafaelpontezup commented on src/main/java/br/com/zup/pagamentos/gateway/TangoGateway.java
> +        return valor.multiply(BigDecimal.valueOf(0.06));
aqui novamente vc está criando `BigDecimal` a partir de `double`. o ideal nesse caso de instanciação explicita eh usar `String` mesmo: `new BigDecimal("0.06")`. outro cuidado eh com a precisão das casas decimais ao trablhar com dinheiro.

aqui um artigo pra vc entender de fato a problemática: https://blog.caelum.com.br/arredondamento-no-java-do-double-ao-bigdecimal/amp/

2021-11-12 14:35 UTC, jacksonmotazup commented on src/main/java/br/com/zup/pagamentos/gateway/RedirecionadorGateways.java
> +        var gatewayEscolhido = this.retornaGatewayMenorTaxa(gateways, transacao.getValor());
feito

2021-11-12 14:36 UTC, jacksonmotazup commented on src/main/java/br/com/zup/pagamentos/gateway/TangoGateway.java
> +        if (valor.doubleValue() <= 100) {
muito chato mexer com operações com BigDecimal kkk, vou arrumar.

2021-11-12 14:38 UTC, jacksonmotazup commented on src/main/java/br/com/zup/pagamentos/gateway/TangoGateway.java
> +        return valor.multiply(BigDecimal.valueOf(0.06));
Então esse método do BigDecimal valueOf(), não é legal usar?

2021-11-16 14:07 UTC, rafaelpontezup requested changes
sugestoes

2021-11-16 14:07 UTC, rafaelpontezup commented on src/main/java/br/com/zup/pagamentos/transacao/Transacao.java
> +    public void concluiTransacaoOnline(RespostaTransacaoGateway respostaTransacao) {
aqui vc está acoplando seu modelo de domínio a classe do gateway `RespostaTransacaoGateway`. Se vc considerar o gateway como parte do seu domínio entao tá tudo bem, mas se vc considerá-lo somente como integrador então talvez seja melhor diminuir esse acoplamento.

2021-11-16 14:07 UTC, rafaelpontezup commented on src/test/java/br/com/zup/pagamentos/gateway/RedirecionadorGatewaysTest.java
> +                () -> assertEquals(valorBigDecimal(0.05), respostaTransacao.taxa()),
de todos os testes que vi este foi o unico que envolveu um valor "quebrado".

se este cenário envolve arredondamento então talvez seja legal deixar isso claro na descrição do método de teste, algo como `Deve redirecionar pro gateway com menor taxa  com valor de pagamento 101.00 mantendo arredondamento` ou nesse estilo.

infelizmente a logica de arredondamento eh implicita pra cobertura de código, vc como dev eh quem tem que enxergar esse cenário e cobri-lo com testes.

2021-11-16 15:31 UTC, jacksonmotazup commented on src/main/java/br/com/zup/pagamentos/gateway/SaoriGateway.java
> +        transacao.conclui();
feito

2021-11-16 15:34 UTC, jacksonmotazup commented on src/main/java/br/com/zup/pagamentos/transacao/Transacao.java
> +    public void concluiTransacaoOnline(RespostaTransacaoGateway respostaTransacao) {
feito

2021-11-16 15:37 UTC, jacksonmotazup commented on src/test/java/br/com/zup/pagamentos/gateway/RedirecionadorGatewaysTest.java
> +                () -> assertEquals(valorBigDecimal(0.05), respostaTransacao.taxa()),
feito

2021-11-16 17:13 UTC, rafaelpontezup reviewed
mais comentarios

2021-11-16 17:13 UTC, rafaelpontezup commented on src/main/java/br/com/zup/pagamentos/transacao/Transacao.java
> +        this.valor = this.valor.subtract(taxa.setScale(2, RoundingMode.HALF_UP));
aqui eh um momento de adicionar validação, coisas como: obrigatoriedade, valores negativos, zerado etc.

2021-11-17 12:13 UTC, merged